apiVersion: template.openshift.io/v1
kind: Template
labels:
  provider: pengg
  template: tarun-pengg-runtime-bc-spog
message: 'The following service(s) have been created in your project: ${BASE}'
metadata:
  annotations:
    description: PENGG - Runtime application build config for SPOG
    iconClass: icon-runtime
    openshift.io/display-name: TARUN PENGG - Runtime application SPOG build config
    tags: 'builder,runtime'
    template.openshift.io/long-description: |
      PENGG - Runtime application build config for SPOG
    template.openshift.io/provider-display-name: NetApp IT Platform Engineering
  name: tarun-pengg-runtime-bc-spog
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the application image
      name: '${BASE}'
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        description: Defines how to build the application
      name: '${BASE}-${SOURCE_REPOSITORY_REF}'
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: '${BASE}:${SOURCE_REPOSITORY_REF}'
      source:
        contextDir: '${CONTEXT_DIR}'
        git:
          ref: '${SOURCE_REPOSITORY_REF}'
          uri: '${SOURCE_REPOSITORY_URL}'
        secrets:
          - secret:
              name: '${GIT_PULL_SECRET}'
        sourceSecret:
          name: '${GIT_PULL_SECRET}'
        type: Git
      strategy:
        sourceStrategy:
          env:
            - name: ANGULAR_HOME_DIR
              value: '${ANGULAR_HOME_DIR}'
          from:
            kind: ImageStreamTag
            name: '${BUILDER_IMAGE_TAG}'
            namespace: '${BUILDER_IMAGE_NAMESPACE}'
        type: Source
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        build: '${BASE}'
      name: '${BASE}-${SOURCE_REPOSITORY_REF}-pipeline'
    spec:
      runPolicy: Serial
      source:
        contextDir: jenkins
        git:
          ref: ${SOURCE_REPOSITORY_REF}
          uri: ${SOURCE_REPOSITORY_URL}
        sourceSecret:
          name: tarun-spog-master
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          env:
            - name: BASE
              value: ${BASE}
            - name: SOURCE_REPOSITORY_URL
              value: ${SOURCE_REPOSITORY_URL}
            - name: SOURCE_REPOSITORY_REF
              value: ${SOURCE_REPOSITORY_REF}
            - name: GIT_PULL_SECRET
              value: tarun-spog-master
            - name: BUILD_NAMESPACE
              value: nss
            - name: DEPLOY_NAMESPACE
              value: tarun-spog1
            - name: OCP_TEMPLATES_SRC_REPOSITORY_URL
              value: git@github.com:tarunaz/pengg-openshift.git
            - name: OCP_DEPLOY_URL
              value: https://tpaas-console.netapp.com:8443
            - name: OCP_BUILD_TEMPLATES_LOC
              value: pengg-openshift/pengg-openshift-system/openshift/templates/pengg-runtime-bc-spog.yaml
            - name: OCP_DEPLOY_TEMPLATES_LOC
              value: pengg-openshift/pengg-openshift-system/openshift/templates/pengg-spog-dc.yml"
          jenkinsfilePath: spogDev1Pipeline.groovy
      type: JenkinsPipeline
      triggers:
        - imageChange:
            from:
              kind: ImageStreamTag
              name: '${BUILDER_IMAGE_TAG}'
              namespace: '${BUILDER_IMAGE_NAMESPACE}'
          type: ImageChange
        - type: ConfigChange
        - generic:
            secret: '${GIT_WEBHOOK_SECRET}'
          type: Generic
parameters:
  - description: The name assigned to all of the frontend objects defined in this template.
    displayName: Name
    name: BASE
    required: true
  - description: The URL of the repository with your application source code.
    displayName: Git Repository URL
    name: SOURCE_REPOSITORY_URL
    required: true
  - description: >-
      Set this to a branch name, tag or other ref of your repository if you are
      not using the default branch.
    displayName: Git Reference
    name: SOURCE_REPOSITORY_REF
    required: true
    value: master
  - description: >-
      Set this to the relative path to your project if it is not in the root of
      your repository.
    displayName: Context Directory
    name: CONTEXT_DIR
  - description: Set Version File location
    displayName: Version file location from gitlab SRC
    name: Version_File_Loc
    required: true
  - description: Set angular source Root
    displayName: ANGULAR_HOME_DIR
    name: ANGULAR_HOME_DIR
  - description: Set image tag of meteor build image
    displayName: Builder ImageTag
    name: BUILDER_IMAGE_TAG
    required: true
    value: 'pengg-s2i-node-angular:latest'
  - description: Set namespace of meteor build image
    displayName: Builder Image Namespace
    name: BUILDER_IMAGE_NAMESPACE
    required: true
    value: pengg
  - description: A secret string used to configure the Generic webhook.
    displayName: Generic Webhook Secret
    from: '[a-zA-Z0-9]{10}'
    generate: expression
    name: GIT_WEBHOOK_SECRET
